### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by sanrita** [RafPe/serverless-reqvalidator-plugin#15]
Hi,

Now that we can do the configuration using a typescript file (https://github.com/serverless/serverless/pull/7934/commits/4fcb4102aef3754e23a42b5a9b57465e6452dede), can there be typescript support for plugins , serverless-reqvalidator-plugin and serverless-aws-documentation (e.g @types/serverless-aws-documentation and @types/serverless-reqvalidator-plugin)

**Comment by sanrita** [comment]
I do see that the serverless-reqvalidator-plugin is kind of now replaced by the schema, perhaps we only require types for the documentation plugin then

**Comment by RafPe** [comment]
@sanrita if you would need TS support PRs are welcome :)  - since TS  is not  my strongest engineering side
