### ISSUE TITLE
Validation warning during deployment

### ISSUE THREAD

**Issue by nakulp007** [RafPe/serverless-reqvalidator-plugin#16]
Getting following validation warning during deployment

> Serverless: Configuration warning:
> Serverless:   at 'functions.category.events[0].http': unrecognized property 'reqValidatorName'
> Serverless:   at 'functions.category.events[0].http': unrecognized property 'documentation'

I have added the following to package.json dependencies

> "serverless-aws-documentation": "^1.1.0",
> "serverless-reqvalidator-plugin": "^1.0.3"

	
And the plugins to serverless.yaml file

> plugins:
>   - serverless-reqvalidator-plugin
>   - serverless-aws-documentation

  
The warning comes when running 'sls deploy' command.

According to this documentation, this warning comes when serverless tries to validate the configuration using AJV and the configuration does not meet expectation. 
https://www.serverless.com/framework/docs/configuration-validation/

Does the plugin need to extend validation schema?
https://www.serverless.com/framework/docs/providers/aws/guide/plugins/#extending-validation-schema

**Comment by RafPe** [comment]
Looks good to fix - I will check that out. Most likely next week something will move as this week I'm absolutely occupado :)
