### ISSUE TITLE
Cannot read property 'defineFunctionEventProperties' of undefined

### ISSUE THREAD

**Issue by juniebonifacio** [RafPe/serverless-reqvalidator-plugin#19]
Looks like the same error was reported in this link https://forum.serverless.com/t/error-at-request-validator-plugin/13596 a couple of days back.

The issue seems to be related to version 1.0.4 which was just very recently committed 5 days ago:

![image](https://user-images.githubusercontent.com/5106213/103993969-51f5a580-51d1-11eb-8d38-b40f5d4eb42d.png)

Please find below my error log:

build	08-Jan-2021 02:54:10	  Type Error ---------------------------------------------
build	08-Jan-2021 02:54:10	 
build	08-Jan-2021 02:54:10	  Cannot read property 'defineFunctionEventProperties' of undefined
build	08-Jan-2021 02:54:10	 
build	08-Jan-2021 02:54:10	     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
build	08-Jan-2021 02:54:10	 
build	08-Jan-2021 02:54:10	  Stack Trace --------------------------------------------
build	08-Jan-2021 02:54:10	 
build	08-Jan-2021 02:54:10	TypeError: Cannot read property 'defineFunctionEventProperties' of undefined
build	08-Jan-2021 02:54:10	    at new ServerlessReqValidatorPlugin (/bamboo-data/bamboo-home/xml-data/build-dir/240222214/Core/node_modules/serverless-reqvalidator-plugin/src/index.js:50:36)
build	08-Jan-2021 02:54:10	    at PluginManager.addPlugin (/opt/node-v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:52:28)
build	08-Jan-2021 02:54:10	    at plugins.forEach (/opt/node-v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:92:14)
build	08-Jan-2021 02:54:10	    at Array.forEach (<anonymous>)
build	08-Jan-2021 02:54:10	    at PluginManager.loadPlugins (/opt/node-v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:88:13)
build	08-Jan-2021 02:54:10	    at PluginManager.loadServicePlugins (/opt/node-v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:141:10)
build	08-Jan-2021 02:54:10	    at PluginManager.loadAllPlugins (/opt/node-v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:84:10)
build	08-Jan-2021 02:54:10	    at service.load.then (/opt/node-v8.12.0/lib/node_modules/serverless/lib/Serverless.js:70:28)
build	08-Jan-2021 02:54:10	    at <anonymous>
build	08-Jan-2021 02:54:10	From previous event:
build	08-Jan-2021 02:54:10	    at runCallback (timers.js:810:20)
build	08-Jan-2021 02:54:10	    at tryOnImmediate (timers.js:768:5)
build	08-Jan-2021 02:54:10	    at processImmediate [as _immediateCallback] (timers.js:745:5)
build	08-Jan-2021 02:54:10	From previous event:
build	08-Jan-2021 02:54:10	    at /opt/node-v8.12.0/lib/node_modules/serverless/bin/serverless:29:46
build	08-Jan-2021 02:54:10	    at Object.<anonymous> (/opt/node-v8.12.0/lib/node_modules/serverless/bin/serverless:66:4)
build	08-Jan-2021 02:54:10	    at Module._compile (module.js:653:30)
build	08-Jan-2021 02:54:10	    at Object.Module._extensions..js (module.js:664:10)
build	08-Jan-2021 02:54:10	    at Module.load (module.js:566:32)
build	08-Jan-2021 02:54:10	    at tryModuleLoad (module.js:506:12)
build	08-Jan-2021 02:54:10	    at Function.Module._load (module.js:498:3)
build	08-Jan-2021 02:54:10	    at Function.Module.runMain (module.js:694:10)
build	08-Jan-2021 02:54:10	    at startup (bootstrap_node.js:204:16)
build	08-Jan-2021 02:54:10	    at bootstrap_node.js:625:3

**Comment by RafPe** [comment]
Hi @juniebonifacio I have replied in the thread on the forum but also in previously opened issue. It comes down to the fact that version 1.0.4 introduces validation map for serverless. 

Therefore if you are unable to upgrade serverless framework used - please use plugin version 1.0.3

**Comment by juniebonifacio** [comment]
Thank you very much @RafPe .
