### ISSUE TITLE
Can't reference Validator created in another Stack

### ISSUE THREAD

**Issue by pj035** [RafPe/serverless-reqvalidator-plugin#2]
I am using multiple stacks with a shared API Gateway (see [serverless docs](https://serverless.com/framework/docs/providers/aws/events/apigateway/#share-api-gateway-and-api-resources)). One stack defines the request validators and exports their reference via [Outputs](https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-cloudformation-outputs). The other stack imports them via 
```
reqValidatorName: 
  Fn::ImportValue: '<others-stack-output-name>'
```

The CloudFormation template validation fails due to `Template format error: Unresolved resource dependencies [[object Object]] in the Resources block of the template` . I tracked this down to this [line](https://github.com/RafPe/serverless-reqvalidator-plugin/blob/master/src/index.js#L74).

A simple check for the type of the `reqValidatorName` and setting the object itself solved my problem (just a workaround):

```
switch (typeof event.http.reqValidatorName) {
  case 'object':
    resources[methodName].Properties.RequestValidatorId = event.http.reqValidatorName;
    break;
  case 'string':
  default:
  resources[methodName].Properties.RequestValidatorId = {"Ref": `${event.http.reqValidatorName}`};
    break;
}
```

**Comment by RafPe** [comment]
I have not tested that scenario - plugin just comes based on my needs where I had one single stack. 

Would you be maybe interested in contributing and doing PR ?

**Comment by pj035** [comment]
Yeah I might give it a try in the upcoming days. I hope I have enough time. Otherwise I'll let you know.
