### ISSUE TITLE
TypeError: serverless.configSchemaHandler.defineFunctionEventProperties is not a function

### ISSUE THREAD

**Issue by andrey613** [RafPe/serverless-reqvalidator-plugin#23]
I have this error when I try to run "serverless offline start". 
Help please.

**Comment by RafPe** [comment]
Please look at https://github.com/RafPe/serverless-reqvalidator-plugin/releases/tag/v1.0.4 and also on #20 and #19 

It boils down to you running not updated SLS framework.
