### ISSUE TITLE
If you introduce a breaking change, you should increment the major version number

### ISSUE THREAD

**Issue by christopherchubb** [RafPe/serverless-reqvalidator-plugin#24]
On your notes for https://github.com/RafPe/serverless-reqvalidator-plugin/releases you say this is a breaking change and I can confirm that my serverless scripts won't finish loading plugins if the version is upgraded from 1.0.3 to 1.0.4. By semver standards, the latest version should be at least 1.1, but really 2.0.

**Comment by RafPe** [comment]
Hey @christopherchubb - thats true - should have been done differently. Will keep this in mind for next releases. Thx
