### ISSUE TITLE
reqValidatorName should be optional in validation

### ISSUE THREAD

**Issue by jasonbrent** [RafPe/serverless-reqvalidator-plugin#26]
It is possible to have an API configuration where only certain end point methods need validation in the same serverless.yml configuration.

In my local tree, I changed 'required' to 'optional' in schema validation to achieve the desired result.

**Comment by RafPe** [comment]
@jasonbrent PRs are always welcome 😇

**Comment by RafPe** [comment]
Closed by #27 and major version 2.0.0 published. This should get u going.
