### ISSUE TITLE
ERR! 404 Not Found: installing serverless-reqvalidator via serverless plugin cmd

### ISSUE THREAD

**Issue by juheba** [RafPe/serverless-reqvalidator-plugin#30]
Executeing the command `serverless plugin install -n serverless-reqvalidator `
results in `npm ERR! 404 Not Found - GET https://registry.npmjs.org/serverless-reqvalidator - Not found`.

![image](https://user-images.githubusercontent.com/47452856/178157727-de49334a-2823-45de-ad88-f8ed225ff5c6.png)

**`package.json`** content:
```json
"dependencies": {
  "serverless-reqvalidator-plugin": "^2.0.0"
},
"devDependencies": {
  "serverless": "^3.0.0",
  "serverless-aws-documentation": "^1.1.0",
}
```
setup:
```sh
$ npm -v
8.3.0

$ sls -v
Running "serverless" from node_modules
Framework Core: 3.19.0 (local) 3.15.0 (global)
Plugin: 6.2.2
SDK: 4.3.2

$ node -v
v12.22.1

$ sh --version
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
...

$ systeminfo
OS:         Microsoft Windows 10 Pro
Version:    10.0.19044 (21H2 Build 19044.1766)
...
```

Website is offline too: https://rafpe.ninja/2017/12/18/serverless-own-plugin-to-attach-aws-api-gateway-basic-request-validation/

**Comment by RafPe** [comment]
@juheba Thanks for opening the issue. I have not worked on the project for a while but I can still see the package on the npm under https://www.npmjs.com/package/serverless-reqvalidator-plugin 

Regarding the website  - thanks for pointing it out - still figuring if I will find time to improve on it
