### ISSUE TITLE
validate a path variable ?

### ISSUE THREAD

**Issue by walshe** [RafPe/serverless-reqvalidator-plugin#4]
is it possible ?

**Comment by RafPe** [comment]
@walshe can you provide link to AWS documentation for this ?

**Comment by walshe** [comment]
actually not even sure if its possible, I guess the fact that a path variable is in the url implicitly means that a) its already required and b) its a string

**Comment by RafPe** [comment]
@walshe if you have documentation which shows how we could implement it on AWS then we could take a look. 
Otherwise I think you need to settle for some workaround :O
